name: Open Data Tool Kit
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor
- possible_sources.txt
include:
  - _navigation.json

# This changes the default compilation from "_site" to "docs" so we can host the files on Github Pages
destination: docs

permalink: pretty
highlighter: rouge
incremental: true
markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Code for Aotearoa
  url: http://codeforaotearoa.org

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /uploads/logo.png
logoalt: Not the Code for Aotearoa logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: About the Open Data Tool Kit
  url: about
  internal: true
- text: Learn about Open Data
  url: pages/learn/
  internal: true
  children:
  - text: What is Open Data?
    url:
    internal: true
  - text: Why Open Data?
    url: why-open-data
    internal: true
  - text: Examples of Open Data usage
    url: examples-of-open-data-usage
    internal: true
  - text: Open Data Charter and NZDIMP
    url: open-data-charter-and-nzdimp
    internal: true
- text: Getting Started
  url: getting-started
  internal: true
- text: Access the toolkit
  url: pages/toolkit/
  internal: true
  children:
  - text: Licensing
    url: licensing
    internal: true
  - text: Publishing to data.govt.nz
    url: publishing-data
    internal: true
- text: Join the community
  url: pages/community/
  internal: true
  children:
  - text: New Zealand
    url: new-zealand
    internal: true
  - text: International
    url: international
    internal: true
- text: Give us feedback
  url: feedback
  internal: true
- text: About
  url: about
  internal: true

repos:
- name: Open Data Tool Kit Github Repo
  description: Toolkit Github repository
  url: https://github.com/codeforaotearoa/open-data-tool-kit

google_analytics_ua: UA-84242199-2

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"
